OnlineTodo.UI/Models/ErrorViewModel.cs
using System;

namespace OnlineTodo.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OnlineTodo.UI/Models/SettingsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineTodo.UI.Models
{
    public class SettingsModel
    {
        public string WebApiBaseUrl { get; set; }
    }
}

OnlineTodo.UI/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineTodo.UI.Models
{
    public class AuthUser
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

OnlineTodo.UI/Areas/TodoList/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using OnlineTodo.Business.Entities;
using OnlineTodo.Business.Helpers;
using OnlineTodo.UI.Models;

namespace OnlineTodo.UI.Areas.TodoList.Controllers
{
    [Area("TodoList")]
    [Route("Todo/[controller]"), Produces("application/json")]
    [Authorize]
    public class TodoController : Controller
    {
        private readonly IOptions<SettingsModel> appSettings; 

        public TodoController(IOptions<SettingsModel> app)
        {
            appSettings = app;
            ApplicationSettings.WebApiUrl = appSettings.Value.WebApiBaseUrl;
        }

        /// <summary>
        /// The Main Page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return View();
        }

        /// <summary>
        /// Refreshes the todo list after any action
        /// we could technically for performance reasons
        /// manipulate the list HOWEVER if we refresh we
        /// are guaranteed that if for some unknown reason the user is adding 
        /// toddo items on 100 different machines, that the proper task list is shown
        /// </summary>
        /// <returns></returns>
        [Route("[action]")]
        [HttpGet]
        [ResponseCache(CacheProfileName = "CacheProfile")]
        
        public JsonResult RefreshTodoList()
        {
            var data = ApiClientFactory.Instance.GetTodoList().Result;

            return new JsonResult(data);
        }

        /// <summary>
        /// Adds a new item to the db
        /// </summary>
        /// <param name="todoItem"></param>
        /// <returns></returns>
        [Route("[action]")]
        [HttpPost]
        public IActionResult AddTodoItem([FromBody] TodoItem todoItem)
        {
            //Move logic to a seperate business layer, controllers
            //should be light weight and business should handle the rest
            TodoItemHelper.AugmentTodoItem(todoItem, User.Identity.Name);

            ApiClientFactory.Instance.SaveTodo(todoItem);
            return Json(new { response = true });
        }

        /// <summary>
        /// Updates a record in the DB
        /// </summary>
        /// <param name="todoItem"></param>
        /// <returns></returns>
        [Route("[action]")]
        [HttpPost]
        public IActionResult UpdateTodoItem([FromBody] TodoItem todoItem)
        {
            ApiClientFactory.Instance.PutTodo(todoItem);
            return Json(new { response = true });
        }

        /// <summary>
        /// Deletes an item from the list
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [Route("[action]")]
        [HttpPost]
        public IActionResult DeleteTodoItem([FromBody]int Id)
        {
            ApiClientFactory.Instance.DeleteTodo(Id);
            return Json(new { response = true });
        }

        /// <summary>
        /// Clears the todo list database
        /// </summary>
        /// <returns></returns>
        [Route("[action]")]
        [HttpPost]
        public IActionResult ClearTodoList()
        {
            ApiClientFactory.Instance.ClearTodo();
            return Json(new { response = true });
        }

    }
}

OnlineTodo.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using OnlineTodo.UI.Models;

namespace OnlineTodo.UI.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [AllowAnonymous, HttpPost]
        public IActionResult Login(AuthUser authUser)
        {
            if (ModelState.IsValid)
            {
                if (authUser.Username == "test" && authUser.Password == "pwd123")
                {
                    var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                    identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, authUser.Username));
                    identity.AddClaim(new Claim(ClaimTypes.Name, authUser.Username));
                    
                    var principal = new ClaimsPrincipal(identity);

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties { IsPersistent = true });
                    
                    return Redirect("~/Home/Index");
                }
                else
                {
                    ModelState.AddModelError("", "Login failed. Please check Username and/or password");
                }
            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineTodo.UI/Areas/TodoList/Views/Todo/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta charset="utf-8" />
    <script>
        var APP_PATH = '@Url.AbsoluteContent("~/")'
    </script>
</head>

<form name="TodoForm" id="TodoForm" ng-app="app" ng-controller="TodoItemCtrl" novalidate>

    <div class="panel-heading"><h4>Add New Task</h4></div>
    <div class="panel-body">

        <div class="col-md-12">
            <div class="col-md-5">
                <div class="pull-left">Description</div>
                <input type="text" class="form-control" ng-required="true" ng-model="TodoItem.Description" />
            </div>
            <div class="col-md-5">
                <div class="pull-left">Due Date</div>
                <input type="date" class="form-control"  ng-required="true" ng-model="TodoItem.DueDate" />
            </div>
            <div class="col-md-2">
                <input class=".btn" type="button" ng-click="AddTodoItemToList();" value="Add Todo Item" />
            </div>
        </div>
    </div>

    <table class="table" ng-show="TodoList.length > 0">
        <thead>
            <tr>
                <th scope="col">Complete</th>
                <th scope="col">Description</th>
                <th scope="col">Created Date</th>
                <th scope="col">Due Date</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat-start="(key, value) in TodoList">
                <td><input type="checkbox" ng-checked="value.complete" ng-click="UpdateTodoItem(value.id,$event);" /></td>
                <td>{{value.description}}</td>
                <td>{{value.createdDate}}</td>
                <td>{{value.dueDate}}</td>
                <td><input type="button" ng-click="DeleteTodoItem(value.id);" value="Delete" /></td>
            </tr>
            <tr ng-repeat-end=""></tr>
        </tbody>
    </table>

    <div ng-show="TodoList.length == 0">
        There were no tasks found, use the add button to add a new task
    </div>

    <input class=".btn pull-right" type="button" ng-click="ClearList();" value="Clear My Todo List" />
</form>

OnlineTodo.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>
    Welcome to the Online Todo List
</h1>

<div class="row">
    <div class="col-md-6">
        <h2>TODO: Upcoming Task Lists go here:</h2>
        <ul>
            <li>Task One</li>
            <li>Task Two</li>
        </ul>
    </div>

</div>

OnlineTodo.UI/Views/Home/Login.cshtml
@model OnlineTodo.UI.Models.AuthUser
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home Page";
}

<h1>Login Page</h1>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    
    @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
    </div>
    
    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
    </div>
    
    <input type="submit" value="Sign In" />
}

OnlineTodo.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineTodo.UI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Online Todo List</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="TodoList" asp-controller="Todo" asp-action="Index">Todo List</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - OnlineTodo.UI</p>
        </footer>
    </div>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>*@
        <script src="~/js/angular.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/angularapp.js" asp-append-version="true"></script>
        <script src="~/js/Views/TodoItemView.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>*@
        <script src="~/js/angular.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/angularapp.js" asp-append-version="true"></script>
        <script src="~/js/Views/TodoItemView.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>